First: Installing the libraries needed for the project:

In [2]:
!pip install pandas
import pandas as pd
!pip install numpy
import numpy as np
!pip install matplotlib
import matplotlib.pyplot as plt
!pip install seaborn
import seaborn as sns

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

Showing csv files details:

In [3]:
df = pd.read_csv('medical_cost_prediction_dataset.csv')
df

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
0,69,Male,29.4,No,1,0,0,0,Medium,14825,4.4,8,1,0,4,Private,80,Semi-Urban,10885,2645.50
1,32,Female,22.9,No,1,0,0,0,Medium,3620,6.0,7,4,3,0,Government,64,Semi-Urban,18722,10959.70
2,89,Male,25.7,No,0,0,0,0,High,10578,4.5,7,2,0,3,NaN,0,Urban,4196,8409.80
3,78,Male,31.9,Yes,0,1,0,0,Low,6226,8.6,9,6,1,7,Government,70,Urban,11128,7996.62
4,38,Male,27.7,No,0,0,0,0,High,6253,5.7,3,6,0,6,Private,77,Urban,15110,3202.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,77,Female,19.7,Yes,0,0,0,0,Low,7825,5.7,3,3,0,4,Government,77,Semi-Urban,17154,3513.76
4996,43,Female,23.9,Yes,0,0,0,0,Medium,9054,8.4,7,4,0,1,NaN,0,Urban,4797,9816.10
4997,58,Female,31.1,No,0,0,0,0,Medium,6299,6.7,3,6,1,2,Private,81,Semi-Urban,16543,3354.62
4998,53,Male,27.6,No,0,0,0,0,Medium,8379,6.2,8,4,0,4,Private,88,Urban,11310,1401.72
4999,40,Male,25.8,No,0,0,0,0,Low,2000,5.3,5,2,1,4,Government,63,Urban,17078,6548.04

In [4]:
# Display the shape of the dataset
df.shape
#Note:The first number are the rows and the second numbers are the columns.

(5000, 20)

In [6]:
# Display a sample of rows
df.head(10)

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
0,69,Male,29.4,No,1,0,0,0,Medium,14825,4.4,8,1,0,4,Private,80,Semi-Urban,10885,2645.50
1,32,Female,22.9,No,1,0,0,0,Medium,3620,6.0,7,4,3,0,Government,64,Semi-Urban,18722,10959.70
2,89,Male,25.7,No,0,0,0,0,High,10578,4.5,7,2,0,3,NaN,0,Urban,4196,8409.80
3,78,Male,31.9,Yes,0,1,0,0,Low,6226,8.6,9,6,1,7,Government,70,Urban,11128,7996.62
4,38,Male,27.7,No,0,0,0,0,High,6253,5.7,3,6,0,6,Private,77,Urban,15110,3202.52
5,41,Male,25.7,No,0,0,0,0,Medium,14720,7.7,10,5,2,6,Private,89,Urban,18459,3072.16
6,20,Female,23.0,Yes,0,0,0,0,High,14762,4.4,8,5,0,4,Government,71,Rural,10047,4032.19
7,39,Female,22.8,No,0,0,0,0,Low,9726,4.6,6,3,1,2,Government,66,Rural,13775,5302.81
8,70,Male,21.7,Yes,0,0,0,0,Low,10800,7.4,8,8,0,2,Government,54,Rural,8289,6411.34
9,19,Male,23.3,No,0,0,0,0,Medium,3398,8.2,4,5,1,4,Government,50,Urban,16291,8983.15

In [5]:
# Display the info of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      5000 non-null   int64
 1   gender                   5000 non-null   object
 2   bmi                      5000 non-null   float64
 3   smoker                   5000 non-null   object
 4   diabetes                 5000 non-null   int64
 5   hypertension             5000 non-null   int64
 6   heart_disease            5000 non-null   int64
 7   asthma                   5000 non-null   int64
 8   physical_activity_level  5000 non-null   object
 9   daily_steps              5000 non-null   int64
 10  sleep_hours              5000 non-null   float64
 11  stress_level             5000 non-null   int64
 12  doctor_visits_per_year   5000 non-null   int64
 13  hospital_admissions      5000 non-null   int64
 14  medication_count         5000 non-null   int64
 15  insurance_type           3952 non-null   object
 16  insurance_coverage_pct   5000 non-null   int64
 17  city_type                5000 non-null   object
 18  previous_year_cost       5000 non-null   int64
 19  annual_medical_cost      5000 non-null   float64
dtypes: float64(3), int64(12), object(5)
memory usage: 781.4+ KB

In [9]:
#Showing the types of each column
df.dtypes

age                          int64
gender                      object
bmi                        float64
smoker                      object
diabetes                     int64
hypertension                 int64
heart_disease                int64
asthma                       int64
physical_activity_level     object
daily_steps                  int64
sleep_hours                float64
stress_level                 int64
doctor_visits_per_year       int64
hospital_admissions          int64
medication_count             int64
insurance_type              object
insurance_coverage_pct       int64
city_type                   object
previous_year_cost           int64
annual_medical_cost        float64
dtype: object

In [11]:
df.isnull().sum()

age                           0
gender                        0
bmi                           0
smoker                        0
diabetes                      0
hypertension                  0
heart_disease                 0
asthma                        0
physical_activity_level       0
daily_steps                   0
sleep_hours                   0
stress_level                  0
doctor_visits_per_year        0
hospital_admissions           0
medication_count              0
insurance_type             1048
insurance_coverage_pct        0
city_type                     0
previous_year_cost            0
annual_medical_cost           0
dtype: int64

Changing all the strings to numbers if possible:

In [15]:
df['gender'] = df['gender'].replace({'Male': 0, 'Female': 1})
"""
Note:
We used the binary datatype where:
Male = 0
Female = 1
"""
# Display the unique values and their counts to verify the transformation
display(df['gender'].value_counts())

gender
1    2519
0    2481
Name: count, dtype: int64

In [16]:
df['physical_activity_level'] = df['physical_activity_level'].replace({'Low': 0, 'Medium': 1, 'High': 2})
"""
Note:
We used the ordinal datatype where:
Low = 0
Medium = 1
High = 2
"""
# Display the unique values and their counts to verify the transformation
display(df['physical_activity_level'].value_counts())

/tmp/ipykernel_4434/3010772027.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['physical_activity_level'] = df['physical_activity_level'].replace({'Low': 0, 'Medium': 1, 'High': 2})

physical_activity_level
0    1996
1    1986
2    1018
Name: count, dtype: int64

In [17]:
df['city_type'] = df['city_type'].replace({'Rural': 0, 'Semi-Urban': 1, 'Urban': 2})
"""
Note:
We used the ordinal datatype where:
Rural = 0
Semi-Urban = 1
Urban = 2
"""
# Display the unique values and their counts to verify the transformation
display(df['city_type'].value_counts())

/tmp/ipykernel_4434/4293941673.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['city_type'] = df['city_type'].replace({'Rural': 0, 'Semi-Urban': 1, 'Urban': 2})

city_type
2    2474
1    1503
0    1023
Name: count, dtype: int64

In [18]:
# Fill missing 'insurance_type' values with the mode
mode_insurance_type = df['insurance_type'].mode()[0]
df['insurance_type'].fillna(mode_insurance_type, inplace=True)

# Display the updated value counts to confirm
display(df['insurance_type'].value_counts(dropna=False))

/tmp/ipykernel_4434/881694044.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['insurance_type'].fillna(mode_insurance_type, inplace=True)

insurance_type
Private       3027
Government    1973
Name: count, dtype: int64

In [19]:
df['insurance_type'] = df['insurance_type'].replace({'Government': 0, 'Private': 1})
"""
Note:
We used the binary datatype where:
Government = 0
Private = 1
"""
# Display the unique values and their counts to verify the transformation
display(df['insurance_type'].value_counts())

/tmp/ipykernel_4434/633244064.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['insurance_type'] = df['insurance_type'].replace({'Government': 0, 'Private': 1})

insurance_type
1    3027
0    1973
Name: count, dtype: int64

In [26]:
df['smoker'] = df['smoker'].replace({'No': 0, 'Yes': 1})
"""
Note:
We used the binary datatype where:
No = 0
Yes = 1
"""
# Display the unique values and their counts to verify the transformation
display(df['smoker'].value_counts())

smoker
0    3779
1    1221
Name: count, dtype: int64

In [27]:
#Showing the types of each column again to check if there are any more strings
df.dtypes
#Now all the table have numbers

age                          int64
gender                       int64
bmi                        float64
smoker                       int64
diabetes                     int64
hypertension                 int64
heart_disease                int64
asthma                       int64
physical_activity_level      int64
daily_steps                  int64
sleep_hours                float64
stress_level                 int64
doctor_visits_per_year       int64
hospital_admissions          int64
medication_count             int64
insurance_type               int64
insurance_coverage_pct       int64
city_type                    int64
previous_year_cost           int64
annual_medical_cost        float64
dtype: object

In [24]:
# Now that all relevant categorical columns are numerical, calculate the correlation matrix
df.corr()

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
age,1.000000,-0.015911,-0.006208,-0.013802,0.010119,0.000437,0.004866,-0.012543,-0.023964,0.000401,-0.009352,-0.024489,-0.013327,0.003540,0.003989,-0.028742,0.003860,-0.002135,0.001083,0.025330
gender,-0.015911,1.000000,0.006778,0.014767,0.020766,0.002233,-0.011684,-0.011970,0.010497,-0.009376,-0.001864,-0.007543,-0.002603,0.006738,0.005030,0.010637,-0.012176,-0.004087,0.002740,0.012557
bmi,-0.006208,0.006778,1.000000,-0.022369,0.008012,-0.008873,0.010854,-0.004920,-0.009413,0.005044,0.007946,0.019086,-0.024716,0.015682,-0.011437,0.001705,-0.013424,0.016935,0.016999,0.031030
smoker,-0.013802,0.014767,-0.022369,1.000000,-0.008585,0.005502,0.000498,0.002044,-0.010640,0.018812,0.008187,-0.012952,-0.013514,0.003225,0.004977,-0.015424,0.017774,-0.028095,0.001080,0.061673
diabetes,0.010119,0.020766,0.008012,-0.008585,1.000000,-0.017362,-0.012147,-0.006789,-0.017698,0.014369,-0.015918,0.037091,-0.012451,0.007036,0.013047,0.010689,0.016322,-0.030949,-0.008866,0.051429
hypertension,0.000437,0.002233,-0.008873,0.005502,-0.017362,1.000000,0.006616,-0.032647,-0.016657,-0.001017,0.009419,-0.023607,-0.008801,-0.001553,-0.004038,-0.027810,-0.002267,-0.034286,-0.009084,0.046926
heart_disease,0.004866,-0.011684,0.010854,0.000498,-0.012147,0.006616,1.000000,-0.014630,0.021395,0.014681,-0.002408,-0.011288,-0.013318,0.000754,-0.005470,-0.008716,-0.024764,0.003408,-0.015565,0.121740
asthma,-0.012543,-0.011970,-0.004920,0.002044,-0.006789,-0.032647,-0.014630,1.000000,-0.007865,0.013272,0.003905,-0.009875,-0.002612,-0.003104,-0.001282,-0.031615,0.016235,-0.005077,-0.011861,0.008869
physical_activity_level,-0.023964,0.010497,-0.009413,-0.010640,-0.017698,-0.016657,0.021395,-0.007865,1.000000,-0.006701,-0.006215,-0.009025,0.007140,0.004619,0.015884,-0.007036,0.023526,0.009101,-0.001901,-0.022504
daily_steps,0.000401,-0.009376,0.005044,0.018812,0.014369,-0.001017,0.014681,0.013272,-0.006701,1.000000,0.010206,0.010099,-0.014183,-0.016815,-0.022136,-0.003983,-0.003148,0.007679,-0.000957,0.001819
sleep_hours,-0.009352,-0.001864,0.007946,0.008187,-0.015918,0.009419,-0.002408,0.003905,-0.006215,0.010206,1.000000,0.018683,0.012188,-0.025556,0.000815,-0.012050,-0.006428,-0.021925,0.019207,-0.004788
stress_level,-0.024489,-0.007543,0.019086,-0.012952,0.037091,-0.023607,-0.011288,-0.009875,-0.009025,0.010099,0.018683,1.000000,0.010225,-0.006105,-0.011701,0.025746,0.010774,-0.011004,-0.013098,0.012596
doctor_visits_per_year,-0.013327,-0.002603,-0.024716,-0.013514,-0.012451,-0.008801,-0.013318,-0.002612,0.007140,-0.014183,0.012188,0.010225,1.000000,-0.014961,-0.012405,-0.034321,0.002070,-0.007788,-0.011704,0.033748
hospital_admissions,0.003540,0.006738,0.015682,0.003225,0.007036,-0.001553,0.000754,-0.003104,0.004619,-0.016815,-0.025556,-0.006105,-0.014961,1.000000,0.025095,0.002080,-0.003211,-0.007675,0.013284,0.355629
medication_count,0.003989,0.005030,-0.011437,0.004977,0.013047,-0.004038,-0.005470,-0.001282,0.015884,-0.022136,0.000815,-0.011701,-0.012405,0.025095,1.000000,0.007721,-0.014845,-0.007070,0.008925,0.133298
insurance_type,-0.028742,0.010637,0.001705,-0.015424,0.010689,-0.027810,-0.008716,-0.031615,-0.007036,-0.003983,-0.012050,0.025746,-0.034321,0.002080,0.007721,1.000000,-0.171363,0.010207,-0.015428,0.143667
insurance_coverage_pct,0.003860,-0.012176,-0.013424,0.017774,0.016322,-0.002267,-0.024764,0.016235,0.023526,-0.003148,-0.006428,0.010774,0.002070,-0.003211,-0.014845,-0.171363,1.000000,-0.011892,0.006946,-0.856152
city_type,-0.002135,-0.004087,0.016935,-0.028095,-0.030949,-0.034286,0.003408,-0.005077,0.009101,0.007679,-0.021925,-0.011004,-0.007788,-0.007675,-0.007070,0.010207,-0.011892,1.000000,0.013278,-0.011098
previous_year_cost,0.001083,0.002740,0.016999,0.001080,-0.008866,-0.009084,-0.015565,-0.011861,-0.001901,-0.000957,0.019207,-0.013098,-0.011704,0.013284,0.008925,-0.015428,0.006946,0.013278,1.000000,0.089275
annual_medical_cost,0.025330,0.012557,0.031030,0.061673,0.051429,0.046926,0.121740,0.008869,-0.022504,0.001819,-0.004788,0.012596,0.033748,0.355629,0.133298,0.143667,-0.856152,-0.011098,0.089275,1.000000

From the correlation before we concluded that the daily_steps, asthma , and sleep_hours have we coleration with annual_medical_cost so we will drop them

In [34]:
df.drop(columns=['daily_steps', 'asthma', 'sleep_hours'], inplace=True)

KeyError: "['daily_steps', 'asthma', 'sleep_hours'] not found in axis"

In [36]:
#Showing all the columns after dropping the unessesary columns
display(df.columns)

Index(['age', 'gender', 'bmi', 'smoker', 'diabetes', 'hypertension',
       'heart_disease', 'physical_activity_level', 'stress_level',
       'doctor_visits_per_year', 'hospital_admissions', 'medication_count',
       'insurance_type', 'insurance_coverage_pct', 'city_type',
       'previous_year_cost', 'annual_medical_cost'],
      dtype='object')